# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 构建并发布包

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 安装 Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install wheel build twine
    - name: 构建sdist
      run: python setup.py sdist
    - name: 构建wheel
      run: python -m build --wheel --no-isolation
    - name: 发布包
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
    - name: 创建 GitHub Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
